services:
  upgrade:
    image: docker.io/library/alpine:${ALPINE_VERSION}
    command: /bin/ash -c "echo 'upgrade' && sleep ${sleep.time}"
    ports:
      - "http.port:80"
      - name: https
        target: 443
        published: https.port
        protocol: tcp
        app_protocol: http
        mode: host
